platform :ios, '10.0'
use_frameworks!

target 'ios-objc-itunes-search' do
  # ignore all warnings from all pods
  inhibit_all_warnings!

  pod 'AFNetworking', '3.1.0'
  pod 'Reachability', '3.2'
  pod 'FMDB', '2.7.2'
  pod 'SVProgressHUD', '2.2.1'

  target 'ios-objc-itunes-searchTests' do
    inherit! :search_paths
  end

end

